//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOValueToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Preconcrete.Commands;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Values
{
    /// <summary>
    /// Subscribes UnityEvent to SOValue. 
    /// And in OnEnable invokes UnityEvent with SOValue (Unlike SOEvent version of such script, that only waits for event).
    /// </summary>
    [AddComponentMenu("UKnack/SOValueToUnityEventAdapters/SOValue_Vector3Int_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOValueToUnityEventAdapter_Concrete_Vector3Int : AbstractCommandSubscribedToSOEvent<Vector3Int>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<Vector3Int>), nameof(IEvent<Vector3Int>.Validate))] 
        private SOEvent<Vector3Int> _subscribedTo;

        [SerializeField]
        private UnityEvent<Vector3Int> _unityEvent;

        [SerializeField]
        [Tooltip("Subscribes UnityEvent to SOValue, OnEnable invokes UnityEvent with value of SOValue")]
        [ValidReference(typeof(IValue<Vector3Int>), nameof(IValue<Vector3Int>.Validate))] 
        private SOValue<Vector3Int> _value;

        private new void OnEnable()
        {
            base.OnEnable();
            _unityEvent?.Invoke(_value.GetValue());
        }

        protected override IEvent<Vector3Int> SubscribedTo => 
            IEvent<Vector3Int>.Validate(_subscribedTo);

        public override void Execute(Vector3Int v) => 
            _unityEvent?.Invoke(v);
    }
}

