//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from DependantUIElement
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------




#nullable disable

using UKnack.Attributes;
using UKnack.UI;
using UnityEngine;
using UnityEngine.UIElements;

namespace UKnack.Preconcrete.UI.Dependants;

public abstract class DependantUIElement_Toggle : Dependant
{
    [SerializeField]
    [DisableEditingInPlaymode]
    private string _toggleName;

    protected Toggle _toggle { get; private set; }

    protected abstract void LayoutReadyAndElementFound(VisualElement layout);
    protected abstract void LayoutCleanupBeforeDestruction();

    protected override void OnLayoutCreatedAndReady(VisualElement layout)
    {
        _toggle = layout.Q<Toggle>(_toggleName);
        ThrowIfNotFoundVisualElement(_toggleName, _toggle);
        LayoutReadyAndElementFound(layout);
    }

    protected override void OnLayoutGonnaBeDestroyedNow() =>
        LayoutCleanupBeforeDestruction();

    protected static void ThrowIfNotFoundVisualElement(string id, VisualElement ve)
    {
        if (ve == null)
            throw new System.ArgumentNullException($"button with id: {id} not found in UIDocument");
    }
}


