//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_ValueSO
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using UKnack.Values;
using UKnack.Preconcrete.Values;

namespace UKnack.Concrete.Values
{

[CreateAssetMenu(fileName = "SOValue_long", menuName = "UKnack/SOValueMutable/long", order = 110)]
public sealed class SOValueMutable_Concrete_long : SOValueMutable<long>
    {
        [SerializeField] 
        private USetOrDefault<long> _value;

        public override long RawValue { get => _value.Value; protected set => _value.Value = value; }


    }

}
