//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_byte_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_byte : AbstractCommandSubscribedToSOEvent<byte>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<byte>), nameof(IEvent<byte>.Validate))] 
        private SOEvent<byte> _subscribedTo;

        [SerializeField]
        private UnityEvent<byte> _unityEvent;

        protected override IEvent<byte> SubscribedTo => 
            IEvent<byte>.Validate(_subscribedTo);

        public override void Execute(byte b) => 
            _unityEvent?.Invoke(b);

    }
}

