//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from SOEventToUnityEventAdapter_FromGeneric
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Events;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Preconcrete.Commands;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{
    /// <summary>
    /// Subscribes UnityEvent to SOEvent. 
    /// </summary>
    [AddComponentMenu("UKnack/SOEventToUnityEventAdapters/SOEvent_short_toUnityEvent")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SOEventToUnityEventAdapter_Concrete_short : AbstractCommandSubscribedToSOEvent<short>
    {
        [SerializeField]
        [ValidReference(typeof(IEvent<short>), nameof(IEvent<short>.Validate))] 
        private SOEvent<short> _subscribedTo;

        [SerializeField]
        private UnityEvent<short> _unityEvent;

        protected override IEvent<short> SubscribedTo => 
            IEvent<short>.Validate(_subscribedTo);

        public override void Execute(short num) => 
            _unityEvent?.Invoke(num);

    }
}

