//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_short", menuName = "UKnack/Publishers/To short")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_short : SOPublisher<short>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<short>), nameof(IEvent<short>.Validate),
        typeof(SOEvent<short>),
        typeof(SOEvent_Concrete_short)
        , typeof(SOValueMutable_Concrete_short)
    )] private SOEvent<short> where;

    public override void Publish(short num)
    {
        ValidateWhere();
        where.InternalInvoke(num);
    }

    internal void ValidateWhere() =>
        IEvent<short>.Validate(where);

}

}

