//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from Concrete_SOEventS
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------
using UnityEngine;
using UKnack.Attributes;
using UKnack.Events;
using UKnack.Concrete.Values;

using static UnityEngine.InputSystem.InputAction;

namespace UKnack.Concrete.Events
{

/// This class not intended to be used in code, but only made for ease of creation scriptable object in Unity Editor
[CreateAssetMenu(fileName = "PublisherToSOEvent_Vector3Int", menuName = "UKnack/Publishers/To Vector3Int")]
[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
internal class SOPublisher_Concrete_Vector3Int : SOPublisher<Vector3Int>
{
    [SerializeField]
    [ValidReference(typeof(IEvent<Vector3Int>), nameof(IEvent<Vector3Int>.Validate),
        typeof(SOEvent<Vector3Int>),
        typeof(SOEvent_Concrete_Vector3Int)
        , typeof(SOValueMutable_Concrete_Vector3Int)
    )] private SOEvent<Vector3Int> where;

    public override void Publish(Vector3Int v)
    {
        ValidateWhere();
        where.InternalInvoke(v);
    }

    internal void ValidateWhere() =>
        IEvent<Vector3Int>.Validate(where);

}

}

