//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from ProUIUpdaterConcrete
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using System.ComponentModel;
using UKnack.Attributes;
using UKnack.SOValues;
using UKnack.Values;

namespace UKnack.Concrete.UI.Dependants
{

[AddComponentMenu("UKnack/UIDependant/UIUpdater/UIUpdaterFromValueSO_bool")]
[EditorBrowsable(EditorBrowsableState.Never)]
[Browsable(false)]
public sealed class UIUpdaterFromSOValue_bool : UIUpdaterFromSOValue<bool>
{
    [SerializeField][ValidReference(nameof(ValidIValue))] private SOValue<bool> _value;

    protected override IValue<bool> GetValueProvider() 
        => ValidIValue(_value);

    protected override string RawValueToStringConversion(bool value)
        => value.ToString();
    

    public static IValue<bool> ValidIValue(UnityEngine.Object value)
    {
        if (value==null)
            throw new System.ArgumentNullException(nameof(value));
        var asIValue = value as IValue<bool>;
        if (asIValue == null)
            throw new System.InvalidCastException($"{value.GetType()} is not compatible with {typeof(IValue<bool>)}");
        return asIValue;
    }
}

}
