//----------------------------------------------------------------------------------------
// <auto-generated> This code was generated from ProUIUpdaterConcrete
// Changes will be lost if the code is regenerated.</auto-generated>
//----------------------------------------------------------------------------------------

using UnityEngine;
using System.ComponentModel;
using UKnack.Attributes;
using UKnack.SOValues;
using UKnack.Values;

namespace UKnack.Concrete.UI.Dependants
{

[AddComponentMenu("UKnack/UIDependant/UIUpdater/UIUpdaterFromValueSO_float")]
[EditorBrowsable(EditorBrowsableState.Never)]
[Browsable(false)]
public sealed class UIUpdaterFromSOValue_float : UIUpdaterFromSOValue<float>
{
    [SerializeField][ValidReference(nameof(ValidIValue))] private SOValue<float> _value;

    protected override IValue<float> GetValueProvider() 
        => ValidIValue(_value);

    protected override string RawValueToStringConversion(float value)
        => value.ToString();
    

    public static IValue<float> ValidIValue(UnityEngine.Object value)
    {
        if (value==null)
            throw new System.ArgumentNullException(nameof(value));
        var asIValue = value as IValue<float>;
        if (asIValue == null)
            throw new System.InvalidCastException($"{value.GetType()} is not compatible with {typeof(IValue<float>)}");
        return asIValue;
    }
}

}
